version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "if [ ! -f /app/db_initialized ]; then
               python manage.py migrate &&
               touch /app/db_initialized;
             fi &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app 
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - API_URL=${API_URL}
      - API_AUTHORIZATION=${API_AUTHORIZATION}
      - SQL_FILE_PATHS=${SQL_FILE_PATHS}
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: leave_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
