# Generated by Django 5.0.6 on 2024-07-03 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apidataupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_s', models.IntegerField(null=True)),
                ('userId', models.IntegerField(null=True)),
                ('empId', models.CharField(max_length=10, null=True)),
                ('teamManagerId', models.IntegerField(null=True)),
                ('designationId', models.IntegerField(null=True)),
                ('designationName', models.CharField(max_length=100, null=True)),
                ('firstName', models.CharField(max_length=100, null=True)),
                ('middleName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('isHr', models.BooleanField(null=True)),
                ('isSupervisor', models.BooleanField(null=True)),
                ('leaveIssuerId', models.IntegerField(null=True)),
                ('currentLeaveIssuerId', models.IntegerField(null=True)),
                ('issuerFirstName', models.CharField(max_length=100, null=True)),
                ('issuerMiddleName', models.CharField(max_length=100, null=True)),
                ('issuerLastName', models.CharField(max_length=100, null=True)),
                ('currentLeaveIssuerEmail', models.EmailField(max_length=254, null=True)),
                ('departmentDescription', models.TextField(null=True)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('leaveDays', models.IntegerField(null=True)),
                ('reason', models.TextField(null=True)),
                ('leaveStatus', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('responseRemarks', models.TextField(null=True)),
                ('leaveTypeId', models.IntegerField(null=True)),
                ('leaveType', models.CharField(max_length=50, null=True)),
                ('defaultDays', models.IntegerField(null=True)),
                ('transferableDays', models.IntegerField(null=True)),
                ('isConsecutive', models.BooleanField(null=True)),
                ('fiscalId', models.IntegerField(null=True)),
                ('fiscalStartDate', models.DateTimeField(null=True)),
                ('fiscalEndDate', models.DateTimeField(null=True)),
                ('fiscalIsCurrent', models.BooleanField(null=True)),
                ('createdAt', models.DateTimeField(null=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('isAutomated', models.BooleanField(null=True)),
                ('isConverted', models.BooleanField(null=True)),
                ('allocations', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('emp_id', models.CharField(blank=True, max_length=20)),
                ('team_manager_id', models.IntegerField(blank=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('is_hr', models.BooleanField(blank=True)),
                ('is_supervisor', models.BooleanField(blank=True)),
                ('leave_issuer_id', models.IntegerField(blank=True)),
                ('current_leave_issuer_id', models.IntegerField(default=None)),
                ('issuer_first_name', models.CharField(blank=True, max_length=100)),
                ('issuer_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer_last_name', models.CharField(blank=True, max_length=100)),
                ('current_leave_issuer_email', models.EmailField(default='unknown@unknown.com', max_length=254)),
                ('department_description', models.TextField(default=None)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apidataupload.designation')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_days', models.IntegerField()),
                ('reason', models.TextField()),
                ('leave_status', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('response_remarks', models.TextField(blank=True, null=True)),
                ('default_days', models.IntegerField()),
                ('transferable_days', models.IntegerField()),
                ('is_consecutive', models.BooleanField()),
                ('fiscal_id', models.IntegerField()),
                ('fiscal_start_date', models.DateField()),
                ('fiscal_end_date', models.DateField()),
                ('fiscal_is_current', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_automated', models.BooleanField()),
                ('is_converted', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='apidataupload.employee')),
            ],
        ),
    ]
