# Generated by Django 5.0.6 on 2024-07-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidataupload', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleave',
            name='createdat_db',
            field=models.DateTimeField(null=True),
        ),
    ]
