# Generated by Django 5.0.6 on 2024-07-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidataupload', '0003_employeeleave_createdat_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
