# Generated by Django 5.0.6 on 2024-07-10 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apidataupload', '0007_leavetype_leave_leave_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_type_id',
        ),
    ]
