# Generated by Django 4.2.14 on 2024-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidataupload', '0012_alter_employee_current_leave_issuer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current_leave_issuer_email',
            field=models.EmailField(blank=True, default='unknown@unknown.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
