# Generated by Django 4.2.14 on 2024-07-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidataupload', '0013_alter_employee_current_leave_issuer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='is_automated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='is_consecutive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='is_converted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='issuer_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='issuer_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_issuer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
