
    -- Insert filtered results from source_table to destination_table
   MERGE INTO apidataupload_leave as l
										USING
									(SELECT DISTINCT 
									"id_s",
									"empId",
									"leaveIssuerId",
									 "issuerFirstName",
									"issuerMiddleName",
									"issuerLastName",
									"startDate",
									"endDate",
									"leaveDays",
									"reason",
									"leaveStatus",
									"status",
									"responseRemarks",
									"leaveTypeId",
									"defaultDays",
									"transferableDays",
									"isConsecutive",
									"fiscalId",
									"fiscalStartDate",
									"fiscalEndDate",
									"fiscalIsCurrent",
									"createdAt",
									"updatedAt",
									"isAutomated",
									"isConverted"
						FROM apidataupload_employeeleave el
    WHERE el."createdat_db" >=  %s
									) a	
									ON l."id" = a."id_s"
									WHEN NOT MATCHED THEN
										INSERT (
											"id",
									"employee_id",
									"leave_issuer_id",
									"issuer_first_name",
									"issuer_middle_name",
									"issuer_last_name",
									"start_date",
									"end_date",
									"leave_days",
									"reason",
									"leave_status",
									"status",
									"response_remarks",
									"leave_type_id",
									"default_days",
									"transferable_days",
									"is_consecutive",
									"fiscal_id",
									"fiscal_start_date",
									"fiscal_end_date",
									"fiscal_is_current",
									"created_at",
									"updated_at",
									"is_automated",
									"is_converted"
										)
										VALUES (
										"id_s",
										"empId",
										"leaveIssuerId",
										"issuerFirstName",
										"issuerMiddleName",
										"issuerLastName",
										"startDate",
										"endDate",
										"leaveDays",
										"reason",
										"leaveStatus",
										"status",
										"responseRemarks",
										"leaveTypeId",
										"defaultDays",
										"transferableDays",
										"isConsecutive",
										"fiscalId",
										"fiscalStartDate",
										"fiscalEndDate",
										"fiscalIsCurrent",
										"createdAt",
										"updatedAt",
										"isAutomated",
										"isConverted"
										)
									 WHEN MATCHED THEN 
									 		UPDATE SET 
											"id"=a."id_s",
							"employee_id"=a."empId",
							"leave_issuer_id"=a."leaveIssuerId",
							"issuer_first_name"=a."issuerFirstName",
							"issuer_middle_name"=a."issuerMiddleName",
							"issuer_last_name"=a."issuerLastName",
							"start_date"=a."startDate",
							"end_date"=a."endDate",
							"leave_days"=a."leaveDays",
							"reason"=a."reason",
							"leave_status"=a."leaveStatus",
							"status"=a."status",
							"response_remarks"=a."responseRemarks",
							"leave_type_id"=a."leaveTypeId",
							"default_days"=a."defaultDays",
							"transferable_days"=a."transferableDays",
							"is_consecutive"=a."isConsecutive",
							"fiscal_id"=a."fiscalId",
							"fiscal_start_date"=a."fiscalStartDate",
							"fiscal_end_date"=a."fiscalEndDate",
							"fiscal_is_current"=a."fiscalIsCurrent",
							"created_at"=a."createdAt",
							"updated_at"=a."updatedAt",
							"is_automated"=a."isAutomated",
							"is_converted"=a."isConverted";
												
